### ISSUE TITLE
Support .jscsrc file outwith project tree

### ISSUE THREAD

**Issue by manderson23** [globexdesigns/brackets-jscs#11]
I would like to share the same .jscrc configuration between multiple projects. However, searching for a .jscrc stops at the project root.

Could support for a global default config file or scanning beyond the project root be supported? For example, the Brackets JSHint extension supports scanning the complete parent tree to find a configuration file.

**Comment by red2678** [comment]
:+1:  This would be huge!

**Comment by rajsite** [comment]
Being able to place a jshintrc and a jscsrc in the same folder (shared by multiple children projects) would be great, either by scanning the same way as jshint or with a config setting.

**Comment by globexdesigns** [comment]
The extension v0.6.0 now supports walking up directories to look for config files. It will look for the nearest config file from the file you're currently editing.

However, 0.6.0 requires that you have JSCS installed globally via:

```npm install -g jscs```
