### ISSUE TITLE
Node-shebangs (#!...) gives errors...

### ISSUE THREAD

**Issue by hacker112** [globexdesigns/brackets-jscs#16]
...Which works fine in JSCS CLI.

![jscs-brackets-shebang](https://cloud.githubusercontent.com/assets/620746/6638220/f2f37200-c983-11e4-9cb2-2de2fd26bfad.png)

**Comment by hacker112** [comment]
Created pull request to fix this issue:

https://github.com/globexdesigns/brackets-jscs/pull/18

**Comment by globexdesigns** [comment]
v0.3.0 was just pushed to the Brackets Extension registry which completely removes JSX processing, so this patch should no longer be needed.
