### ISSUE TITLE
Rule disallowTrailingWhitespace broken

### ISSUE THREAD

**Issue by hacker112** [globexdesigns/brackets-jscs#17]
The JSCS rule:

```json
{"disallowTrailingWhitespace": true}
```
does not work.

It is cause by the following code most probably:
```javascript
// Trim trailing whitespace
JSXCode = JSXCode.replace(/( +)\n/g, '\n');
```

**Comment by hacker112** [comment]
Why is it necessary to remove trailing whitespace from the JSXTransformer in the first place? Where does it come from?

**Comment by globexdesigns** [comment]
JSXTransformer, unfortunately, does some ugly things - like leaving behind trailing whitespace during certain operations. Since most people don't want trailing whitespace to be allowed - the simplest solution is to simply clear it out.

**Comment by hacker112** [comment]
Since there seems to be some issues with JSXTransformer, and I do not use JSX. I just want to be able to use JSCS in Brackets as it is suppose to work. 

I think most people do not use JSX, I would suggest that we turn it off as default and then add an brackets-setting to turn it on for those who use it. 

Then default behavior would be a plugin that works just like the JSCS should :-)

**Comment by globexdesigns** [comment]
I'm with you. I suspect I'll be adding a GUI to let users select whether or not they want JSX parsing enabled (false being the default).

**Comment by hacker112** [comment]
Great :-) A good start could be to just add it in the brackets.json.

**Comment by globexdesigns** [comment]
v0.3.0 was just pushed to the Brackets Extension registry which completely removes JSX processing, so this patch should no longer be needed.
