### ISSUE TITLE
BUG : "disallowSpacesInsideParentheses" works like "requireSpacesInsideParentheses"

### ISSUE THREAD

**Issue by lmagne** [globexdesigns/brackets-jscs#20]
The error "missing space before closing round bracket" appears when I write in my conf file either "disallowSpacesInsideParentheses": true OR "requireSpacesInsideParentheses": "all"

But in the JSCS Rules, disallowSpacesInsideParentheses is the contrary of requireSpacesInsideParentheses !

Here my jscs.json : 
{
  "preset": "jquery",
  "maximumLineLength": null,
  "requireMultipleVarDecl": null,
  "requireSpacesInsideArrayBrackets": null,
  "disallowSpacesInsideArrayBrackets": "all",
  "validateQuoteMarks": { "mark": "'", "escape": true },
  "disallowSpacesInsideParentheses": true,
  "disallowMixedSpacesAndTabs": true,
  "requireMultipleVarDecl": true,
  "requireBlocksOnNewline": 1
}

**Comment by globexdesigns** [comment]
Sounds like an issue with JSCS itself. Try looking for and posting the issue in: https://github.com/jscs-dev/node-jscs/issues

**Comment by lmagne** [comment]
OK,
Sorry for the time but I need some explanations.
In the jscs-browser.js file, when I comment the line number 28171 (which correspond to "requireSpacesInsideParentheses": "all", in the module 152) , the error don't appear.
After this change, to show the same error, I must add "requireSpacesInsideParentheses": "all" in my jscs.json.
So this module seem's to be the default conf. It's correct ? Event if I choose jquery preset (it's seems there is no changes if I remove the jquery preset in my jscs.json)??

How can I overload, in my jscs.json, this parameter without change the containt in your jscs-browser.js file ?

**Comment by globexdesigns** [comment]
Try `"requireSpacesInsideParentheses": false` instead of `"requireSpacesInsideParentheses": null`

**Comment by lmagne** [comment]
Oops. I have miss a line in the official documentation... I've got a vision after a good night ^^'
Sorry for your loss time.

If I had understand your plugin, you have do the automatisation in bracket, all the logic come from node-jscs without changes. Is it correct ?
Thank you for your answers !

**Comment by globexdesigns** [comment]
That's correct. This extensions just runs your code through node-jscs and prints whatever it finds.
