### ISSUE TITLE
Large Project - Litner Config Not Found

### ISSUE THREAD

**Issue by red2678** [globexdesigns/brackets-jscs#21]
Hi, 

In a few of our large projects (30,000+ files), the litner config is not found and brackets reverts to the default linter settings. 

How can I fix this?

Thanks!!

**Comment by globexdesigns** [comment]
Do you have a .jscsrc file in the root of your project?

**Comment by red2678** [comment]
I have a .jscs.json


~Anthony
*anthonytrimble.com
<https://mailtrack.io/trace/link/b65167329169ad5b51a5948a2e1945d23308a332?url=http%3A%2F%2Fanthonytrimble.com&signature=4e5078859bd34d9b>*​
| *linkedin.com/in/anthonytrimble/
<https://mailtrack.io/trace/link/d092aa511ffaf2f1ae4d90fab9034f812b9516be?url=http%3A%2F%2Flinkedin.com%2Fin%2Fanthonytrimble%2F&signature=8d7bc2b894130430>*

**Comment by red2678** [comment]
I have a .jscs.json

**Comment by red2678** [comment]
FYI, it seems to work when I rename the file to .jscsrc

**Comment by evnaverniouk** [comment]
Can you try this again using 0.6.0?
