### ISSUE TITLE
Cannot find module 'jscs'

### ISSUE THREAD

**Issue by jdelibas** [globexdesigns/brackets-jscs#24]
Ubuntu 15.04 x64
Brackets Release 1.3
JSCS 0.6.3

The removal of local jscs seems to have broke on ubuntu. (only tested on works machine)
I have globally(`npm -g`) installed the package but it refuses to find it...

I had to locally install(`npm`) jscs in  `extensions/user/globaldesigns.brackets-jscs` to get it to work.

Error Message
```
Unexpected JSCS processing error: Unable to load one of the modules: /home/james/.config/Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Cannot find module 'jscs'	```

**Comment by mitorez** [comment]
I get a similar error on:
Windows 7 SP1 Enterprise 64-bit
Brackets 1.3 - Release 1.3 build 1.3.0-16022 (release cd0a6aae5)
JSCS 0.6.3

**Error:**
[NodeDomain] Error loading domain "globexdesigns.brackets-jscs": Unable to load one of the modules: C:/Users/*username*/AppData/Roaming/Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Cannot find module 'jscs'

**Comment by globexdesigns** [comment]
@mitorez The newest version of the extensions requires that you have node.js and jscs installed as a global npm package. Make sure you check out the Installation instructions in the README: https://github.com/globexdesigns/brackets-jscs#installation

**Comment by mitorez** [comment]
@globexdesigns Thanks for the info. I must have misread the commit comment below, b/c it sounded like JSCS was now bundled in the extension. I'll install JSCS via node.
*Fixes #23. JSCS is now bundled with the extension as loading it from global modules doesn't seem to work reliably.*

**Comment by jdelibas** [comment]
When locally installed it works on and off and I am seeing

`JSCS has timed out after waiting for 10000 ms`

Not sure if its related.

**Comment by globexdesigns** [comment]
@mitorez I'm trying to find a way to not bundle JSCS with the extension. There are a couple benefits to this:
- Users can run their own versions of JSCS (allowing them to upgrade at their pace and sync up with their projects)
- Users don't need to wait for me to release extension update to use the latest JSCS build
However, for some reasons, not all users are able to use the global JSCS modules for some reason. It seems to work for most, but not 100%.

@jdelibas This can occur if you have a very large file with many errors or if your file system is slow for some reason. Sometimes, re-saving the file will make it go through. This is Brackets feature to prevent linters from taking too long to run.

**Comment by globexdesigns** [comment]
I pushed a new 0.6.4 version. Can you give that a try?

**Comment by mitorez** [comment]
@globexdesigns My company proxy blocks npm and I haven't had a chance to install JSCS from home yet, so I haven't tested this change - I'll try to install JSCS tonight and test tomorrow. Would you be open to a separate enhance request to include and load JSCS from within your extension if JSCS is not found globally? I'm ok with your extension not always running the latest version of JSCS, since getting JSCS installed via node is currently a pain for me at work.

**Comment by globexdesigns** [comment]
@mitorez  Yes. I've been discussing it with the Brackets team and they recommend building in a feature where the user selects the path to the JSCS module you want to use. With the choices being (global, local project, or whatever is bundled with the brackets-jscs extension). Such a feature might take a bit of time to build though.

**Comment by mitorez** [comment]
@globexdesigns I installed JSCS globally via npm last night and your extension (v0.6.4) is working fine - it no longer writes a 'timeout' message to the code analysis console, it correctly loads the current JSCS errors for the scanned page. Thanks! Though I see you're now bundling JSCS again with v0.6.5.

**Comment by globexdesigns** [comment]
Yeah... I'm giving up the idea of using the global packages. It never seems to work reliable for everyone despite my best efforts.

**Comment by philliprauschkolb** [comment]
I'm on a fresh install of everything and I'm getting the message:

`JSCS has timed out after waiting for 10000 ms`

I've installed JSCS globally first, then the extension but can't get it to work. 

Brackets 1.6
JSCS 3.0.3

**Comment by ericgrosse** [comment]
I'm having the same issue. I'm using Windows 10 and same versions as phil above.

**Comment by EvNaverniouk** [comment]
Sorry guys. I think I'm going to have to drop support for this extension very soon.

- The JSCS and ESLint teams have decided to merge JSCS into ESLint, so it's best that you start migrating your rules to ESLint and the excellent bracket-eslint extension
- I'm not actively using Brackets anymore

If you want to try and take a look yourself and submit a PR I'd be more than happy to review and merge it in.
