### ISSUE TITLE
Unexpectedly stop the node server

### ISSUE THREAD

**Issue by cithukyaw** [globexdesigns/brackets-jscs#26]
When I having this extension installed, I got several errors in developer console. Please check the following screen shot.

![635682783052642734](https://cloud.githubusercontent.com/assets/4285555/7817562/d212dd48-03fb-11e5-8569-f75895a89516.png)

This would cause any extension to be working. [Please check the other issue](https://github.com/mikaeljorhult/brackets-php-code-quality-tools/issues/22#issuecomment-105596826). Probably it is because of I'm running in offline mode (not connected to internet)?

I'm using Brackets 1.3 on Windows 7.

**Comment by globexdesigns** [comment]
You're running an older version of the extension. Try upgrading to the latest version (0.7.0)

**Comment by cithukyaw** [comment]
Got it! Thank you.
