### ISSUE TITLE
JSCS timing out

### ISSUE THREAD

**Issue by maskedcoder** [globexdesigns/brackets-jscs#27]
After upgrading to 0.7.0, JSCS for Brackets is reporting `JSCS has timed out after waiting for 10000 ms` every time it runs.

I'm using Brackets 1.3 on Windows 7.

**Comment by ptakes** [comment]
Same issue, this results in files added to the jscodehints.detectedExclusions list in the project's .brackets.json file.

**Comment by rajsite** [comment]
After upgrading Brackets to 1.3.0-16022 and JSCS 0.7.0 I also see an error from JSCS. The message I see is `Unexpected JSCS processing error: Max connection attempts reached`

I found a similar sounding issue for brackets-git: https://github.com/zaggino/brackets-git/issues/410

The workaround mentioned there is to run the brackets process with admin privileges which worked for me on Win7 64-bit. There is an issue filed to Brackets which sounds related: https://github.com/adobe/brackets/issues/7550

**Comment by globexdesigns** [comment]
The timeout issue should be fixed in 0.7.2. The "max connection" error is something new that I've never seen before...

**Comment by rajsite** [comment]
I have upgraded to 0.7.3 and now when I open multiple instances of Brackets, every instance after the first (i.e. two or more instances) receives the error ```JSCS has timed out after waiting for 10000 ms``` in the linting window.

The Brackets.io JavaScript console show the following:
![capture](https://cloud.githubusercontent.com/assets/1588923/8339080/a2909e26-1a7a-11e5-87e8-064e7ab169b1.PNG)

**Comment by globexdesigns** [comment]
Hmm. I can't seem to be able to reproduce that issue. Have you tried refreshing Brackets? It looks like the node servers for the app failed. Go to "Debug > Reload with Extensions".

**Comment by PStoner3** [comment]
Brackets Build 1.7.0-16898 and JSCS For Brackets 0.7.5 produces same issue.

**Comment by tenacioustechie** [comment]
Likewise, I've hit the same issue with Build 1.7.0-16898 with JSCS for brackets 0.7.5 produces the 'JSCS has timed out after waiting for 10000ms' error message. On Windows 10 x64.

**Comment by geooogle** [comment]
Has any one found a solution to this yet? Thank you in advance!
