### ISSUE TITLE
The JSCS 2.0 does not use esprima anymore

### ISSUE THREAD

**Issue by boldt** [globexdesigns/brackets-jscs#30]
The new JSCS 2.0 does not use esprima anymore. Because of this, I ca not use the same .jscsrc for `grunt jscs` and `brackets-jscs`.

See: https://www.bountysource.com/issues/25066285-unknown-node-type-export-declaration?utm_campaign=plugin&utm_content=tracker%2F281640&utm_medium=issues&utm_source=github

**Comment by globexdesigns** [comment]
- Upgrade to the latest version of `bracket-jscs`.
- Follow the Installation instruction in the README here: https://github.com/globexdesigns/brackets-jscs
- Set your `.jscsrc` file to use `"esprima": "babel-jscs"`

That should work.
