### ISSUE TITLE
Feature request: Add JSCS formatting

### ISSUE THREAD

**Issue by stumblingmages** [globexdesigns/brackets-jscs#33]
Would it be possible to extend this to add the jscs formatting? Per this page it seems like it's done with an option.

https://medium.com/@addyosmani/auto-formatting-javascript-code-style-fe0f98a923b8

**Comment by globexdesigns** [comment]
This is already available. Simply right-click anywhere in the code editor and choose "Auto-fix with JSCS" or go to `Edit > Auto-fix with JSCS`.
