### ISSUE TITLE
Ignored rule: One space required after opening bracket.

### ISSUE THREAD

**Issue by mattez** [globexdesigns/brackets-jscs#34]
JSCS for Bracket ignore rule [requireSpacesInsideBrackets](http://jscs.info/rule/requireSpacesInsideBrackets) which command line tool return correctly as an error. We use "preset": ["jquery"](https://github.com/jscs-dev/node-jscs/blob/master/presets/jquery.json).
This should be evaluated as an error:
```
ab[c][d]
```
and should be auto-fixed to:  
```
ab[ c ][ d ]
```

My JSCS file
```
{
	"preset": "jquery",
	"requireCamelCaseOrUpperCaseIdentifiers": "ignoreProperties",
	"requireCapitalizedComments": { "allExcept": [ "global", "jshint", "jscs" ] }
}
```
This extension save me a lot of time with code style fixing. Thank you.

**Comment by globexdesigns** [comment]
I have tested this rule with the latest version of the extension, and it works fine. Please upgrade and try again.

**Comment by mattez** [comment]
Hi, thanx reply, but it is still same, not working.
How did you test it?

1 - updated to last version.
2 - create new _test.js_ file

Javascript file contains only:
```javascript
ab[c][d]
```
3 - in Brackets > Edit > Auto-fix with JSCS
4 - only adds one line at the end
```javascript
ab[c][d]
<newline>
```
Other example, this
```
[a][b][c]
```
changes to this
```
[ a ][b][c]
<newline>
```

My setup:

* JSCS for Brackets v.0.7.5
* Brackets Release 1.4 experimental build 1.4.0-16380 (release 273804eb3) 
build timestamp: Mon Jul 27 2015 06:50:54 GMT+0000
* Ubuntu 14.04 LTS

I got also this in brackets.json
```json
    "language": {
        "javascript": {
            "linting.prefer": [
                "JSHint",
                "JSCS"
            ],
            "linting.usePreferredOnly": true
        }
    },
```

**Comment by globexdesigns** [comment]
Try this:

```
- Go to `Help > Show Extensions Folder`
- In the extensions folder navigate to `/user/globexdesigns.brackets-jscs`
- Open a terminal to this folder and run `npm install`
- Restart Brackets
```

**Comment by mattez** [comment]
Thanx @globexdesigns this works! Great.
I had a not last version of your extension? or Where was a problem?

**Comment by globexdesigns** [comment]
The latest version of JSCS requires that it is installed directly via `npm`. I cannot bundle it with the extension anymore because it is bigger than the 5MB limit. In order to update JSCS, you need to run `npm install` inside the extension directory.
