### ISSUE TITLE
Support JSCS v2.2.1

### ISSUE THREAD

**Issue by ficristo** [globexdesigns/brackets-jscs#35]
Can be upgraded to support the newer version?

**Comment by globexdesigns** [comment]
v0.7.4 has been published to the Brackets Extension registry with the latest jscs version (v2.3.0)

**Comment by ficristo** [comment]
I installed the new version but now I get this error:
Unexpected JSCS processing error: Unable to load one of the modules: ..../Brackets/extensions/user/globexdesigns.brackets-jscs/domain, reason: Cannot find module 'colors'
