### ISSUE TITLE
I'm getting: Unexpected JSCS processing error: Unable to load one of the modules *  reason: Cannot find module 'color'

### ISSUE THREAD

**Issue by jobsturm** [globexdesigns/brackets-jscs#36]

**Comment by 6ix** [comment]
Same thing here.

**Comment by chdanielmueller** [comment]
Same problem here

**Comment by globexdesigns** [comment]
I'll push an update with a fix a little later today.

**Comment by globexdesigns** [comment]
Version 0.7.5 has been published. It requires manual installation of JSCS. See Installation instructions here: https://github.com/globexdesigns/brackets-jscs
