### ISSUE TITLE
error after latest update:

### ISSUE THREAD

**Issue by zaggino** [globexdesigns/brackets-jscs#37]
![image](https://cloud.githubusercontent.com/assets/1067319/10896402/f6218604-820d-11e5-9b80-7b690607f598.png)

project: https://github.com/zaggino/z-schema
no mention of airbnb in it

**Comment by globexdesigns** [comment]
Hmm. Nothing in our code loading `airbnb.json`. Are you sure you don't have some `.jscsrc` file in a higher directory that's depending on that preset?

**Comment by zaggino** [comment]
Don't know about it, running `grunt jscs` works fine for me and this extension also worked fine before the update today.

**Comment by globexdesigns** [comment]
Strange. There hasn't even been an update to `brackets-jscs` in the last month. Is this happening for all of your projects, or just the `z-schema` one?

Can you also try running `npm install `inside the `brackets-jscs` extension folder and see if that makes any difference?

**Comment by zaggino** [comment]
Haven't updated for a while, it might have been pending update for some time. Doing `rm -rf node_modules && npm install` did the trick, closing.
