### ISSUE TITLE
JSCS issue "Unexpected JSCS processing error: timeout"

### ISSUE THREAD

**Issue by anilnatha** [globexdesigns/brackets-jscs#38]
I had been using this plugin for about 6 months without issue. After upgrading to Brackets v1.5, build 1.5.0-16538, I noticed that the JSCS information in the output stated the following:

> JSCS has not been installed in the extension. See Installation steps here: https://github.com/globexdesigns/brackets-jscs

So then I went through the installation and configuration information in the readme.md file, noticing that there were extra steps to perform that weren't there previously.  So I reinstalled the plugin via Extension Manager registry to ensure I had the latest version. Ran the `npm install` command as specified in the readme document and checked that my preferences file matches that in the readme.md 'Configuration' Section. Then finally, restarted Brackets.

Now I get the following error and don't know how to proceed with resolving this.

> Unexpected JSCS processing error: timeout

**Comment by anilnatha** [comment]
So I restarted brackets a couple more times, and now JSCS is working as expected. I am unsure why the first, or second restart for that matter didn't work.  Sorry for the trouble.

**Comment by globexdesigns** [comment]
I've noticed this with Brackets sometimes too. The internal Node.js server is sometimes slow to start which results in all extensions that use Node commands to fail. I don't know how to fix this on my end.
