### ISSUE TITLE
Support for the fix parameter

### ISSUE THREAD

**Issue by MagmaRules** [globexdesigns/brackets-jscs#39]
Hi,

Would be great if there was support for the fix parameter so that when saving a file it could be fixed based on the rules used to validate.
Similar to this one: https://atom.io/packages/jscs-fixer

**Comment by globexdesigns** [comment]
It's already possible. There is an "Auto-fix with JSCS" option available in the Edit menu as well as if you right-click anywhere in the editor.

**Comment by MagmaRules** [comment]
Hi,

Yeah I found the option. Tried to make it work on save but seems to be hard at the moment. Without a beforeDocumentSaved event or something: https://github.com/adobe/brackets/issues/2633

**Comment by globexdesigns** [comment]
Yeah, there's no easy way to make it run on save at the moment. But, that might actually be quite dangerous as the JSCS fixer is known to be buggy at times.
